### ISSUE TITLE
Code Highlight Doesn't Work At Delete Time

### ISSUE THREAD

**Issue by jaminn** [YonghoAhn/JSDN_JSS#1]
#include <Stdio.h>> -> > deleted, then code highl한국어
그래서 결론적으로 코드 지울떄 Highlight가 제대로 작동을 안하므로, Key값중에서 Delete나 Backspace 들어올때도 Code Highlight를 재 호출해 주어야 한다.

**Comment by YonghoAhn** [comment]
수정됨
