### ISSUE TITLE
내년엔 부디 일찍 기획내서 WPF로 작성하시길

### ISSUE THREAD

**Issue by jaminn** [YonghoAhn/JSDN_JSS#4]
그러면 디자이너가 시키는 대로 작업도 되고 어 리소스도 잘나오고 어 팍씨 WPF로 하면 UI유연성도 좋고 데이터 바인딩도 쉽고 마 좋은데 왜 WF으로 작업하냐
내년부터는 WPF나 Windows Universal Platform으로 작업하시요

**Comment by YonghoAhn** [comment]
ㅇㅋ
