### ISSUE TITLE
html 테그를 열으면, 자동으로 닫치는 테그">" 앞에 ">"문자를 쓰면 크기가 갑자기 작아집니다.

### ISSUE THREAD

**Issue by jaminn** [YonghoAhn/JSDN_JSS#6]
![egggg](https://cloud.githubusercontent.com/assets/12621878/19836851/1543d4d8-9ef0-11e6-8341-b2ed4e5e4f00.PNG)

**Comment by YonghoAhn** [comment]
Font 강제 설정으로 해결됨
